easyfuse-pipeline:
  image: continuumio/miniconda3:23.5.2-0
  stage: build
  script:
    - conda install -c bioconda nextflow=21.10.0
    - bash test/scripts/test_00.sh

changelog_check:
  stage: test
  script:
    - git fetch
    - FILES_CHANGED=$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA...HEAD)
    - |+
      for i in $FILES_CHANGED
      do
        if [[ "$i" == "CHANGELOG.md" ]]
        then
          exit 0
        fi
      done
      exit 1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'